# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html>
   <head>
      <meta charset=\"UTF-8\" />
      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
      <title>DHT11 Webserver</title>
      <link rel=\"stylesheet\" href=\"static/css/entireframework.min.css\" />
      <link rel=\"stylesheet\" href=\"static/css/index.css\" />
      <!-- Load plotly.js into the DOM -->
      <script src='https://cdn.plot.ly/plotly-2.16.1.min.js'></script>
   </head>
   <body>
      <script src=\"static/js/index.js\"></script>
      <button class=\"btn-close btn btn-sm\">×</button>
      <div class=\"container\">
         <div class=\"hero\">
            <h1 class=\"title\">AER MONITUS</h1>
            <div class=\"graphDiv\">
               <div id='temperatureDiv'>
               </div>
               <div id='humidityDiv'>
               </div>
               <div id='ppmDiv'>
               </div>
            </div>
         </div>
      </div>
   </body>
</html>"""
